# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ob84QlJPipWaH7OOodKZKsz9Mx6NoASp
"""

#importando
import numpy as np
from sklearn.cluster import KMeans
filmes_assistidos = np.array([
    [1, 0, 0, 1],
    [1, 1, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 1, 1],
    [1, 0, 1, 0],
    [1, 0, 1, 0],
    [1, 0, 1, 0],
    [1, 0, 1, 0],
    [1, 0, 1, 0],
])

#Treinar o modelo
#numero de clusters(grupo)
num_clusters = 2

#Inicializando o modelo
kmeans = KMeans (n_clusters=num_clusters,n_init=10)


#Treinando o modelo
kmeans.fit(filmes_assistidos)

#classificados os usuarios
grupos_indice = kmeans.predict(filmes_assistidos)

#Exibir os dados
print("usuario pertence ao seguinte grupo:")
for i, grupo_indice in enumerate(grupos_indice):
    print(f"Usuario {i+1}: Grupo {grupo_indice+1}")

print("\nFilmes assistidos:")
for i in range(len(filmes_assistidos)):
   assistidos = np.where(filmes_assistidos[i] == 1)[0]
   print(f"Usuario {i+1}: {', '.join(map(str, filmes_assistidos[i]))}")


#Função que recomenda filmes
def recomendar_filme(filmes, filmes_assistidos, grupo_indice):

  filmes = np.array(filmes)

  #Encontrar o grupo do usuario com base no seu vetor filmes
  usuario_id = len(filmes_assistidos)
  grupo_usuario = kmeans.predict([filmes])[0]

   #Encontrar todos os usuarios no memso grupo
  usuarios_no_mesmo_grupo = [i for i in range(len(grupos_indice))
  if grupos_indice[i] == grupo_usuario]

  #filmes assistidos pelo usuario no mesmo grupo
  filmes_recomendados = set()
  for usuario in usuarios_no_mesmo_grupo:
   filmes_assistidos_usuario = np.where(filmes_assistidos[usuario] == 1)[0]
   filmes_recomendados.update(filmes_assistidos_usuario)


  #remover filmes que o usuario ja assistiu
  filmes_recomendados = filmes_recomendados - set(filmes_assistidos[usuario])

  #ajustar os indices dos filmes recomendados (de volta para 1- based)
  filmes_recomendados = [filmes[i] for i in filmes_recomendados]

  return sorted(filmes_recomendados)

 #Exemplo de uso da função recomendar_filmes
filmes_assistidos_usuario = [1, 1, 0, 0] # Vetor de filmes

# Assistidos (por exemplo, assistiu aos filmes 1 e 3)
filmes_recomendados = recomendar_filme(filmes_assistidos_usuario, filmes_assistidos, grupos_indice)

print(f"\nFilmes recomendados: {filmes_recomendados}")

